FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

VOLUME /app

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
# RUN echo "while true; do sleep 1000; done" > /test.sh
# CMD ["sh","/test.sh"]